server:
  port: 8081

spring:
  data:
    mongodb:
      username: ${DB_USER:root}
      password: ${DB_PWD:root}
      database: ${DB_NAME:MobBuilder}
      uri: ${MONGODB_URI:mongodb://localhost:27017/}